name: Test

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
      - "uv.lock"
      - "pyproject.toml"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
      - "uv.lock"
      - "pyproject.toml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest
